# Generated by Django 3.2.8 on 2021-10-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.EmailField(max_length=255, null=True),
        ),
    ]
